// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1639601689);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1639601641);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1639601841);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1639601870);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1639601900);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1639601638);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d7939993-154b-4348-8f43-26b54f22bf3c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210804193234");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1639601841");
user_pref("browser.startup.homepage_override.buildID", "20210804193234");
user_pref("browser.startup.homepage_override.mstone", "91.0");
user_pref("browser.startup.lastColdStartupCheck", 1639601841);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1639601640017");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "91.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210804193234");
user_pref("extensions.lastAppVersion", "91.0");
user_pref("extensions.lastPlatformVersion", "91.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"73330ebc-c1e4-40c9-b5ed-c2ea1c6770e1\",\"formautofill@mozilla.org\":\"342ace42-724e-40ce-b647-bf6636379580\",\"pictureinpicture@mozilla.org\":\"b9dd394b-8a3c-4214-9f5b-a8534f7a8d45\",\"screenshots@mozilla.org\":\"616c52a8-a6c3-4174-a14d-9066f97ecbd1\",\"webcompat-reporter@mozilla.org\":\"98bf3aef-c0b0-4975-ba07-b147ef0a7d3d\",\"webcompat@mozilla.org\":\"dbf5eaf3-c5aa-4700-b0c2-7b2c236a2c36\",\"default-theme@mozilla.org\":\"22af6ded-d6e1-49c0-bfe9-f66a003f976c\",\"google@search.mozilla.org\":\"2eab5e9b-356e-45d0-aea3-554e34d372fd\",\"wikipedia@search.mozilla.org\":\"e68a3f8e-a051-4135-b084-ffd77c9d8ff3\",\"bing@search.mozilla.org\":\"7eeb7c2e-54ed-4c0e-9d4a-227ca0c3a5cd\",\"ddg@search.mozilla.org\":\"742c6d1c-0e16-441d-b16d-654ec6c83d0f\",\"ebay@search.mozilla.org\":\"7d806127-fd4e-44a3-b235-6dddc7707944\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1639601640);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20210804193234");
user_pref("media.gmp-manager.lastCheck", 1639601680);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2b501987-f415-4e8b-8999-d838d7a8d348");
user_pref("toolkit.startup.last_success", 1639601839);
user_pref("toolkit.telemetry.cachedClientID", "c9c8f635-da7e-4e5c-a4f0-d0354ed21125");
user_pref("toolkit.telemetry.previousBuildID", "20210804193234");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
